name: CI Pipeline
on:
  push:
  branch_protection_rule:
    types: [created, deleted]

  public:
  pull_request:
  release:
    types: [published]

  status:

env:
  BUILD_CACHE: 'gradle'
  JAVA: '17.0.6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA }}
          cache: ${{ env.BUILD_CACHE }}
      - name: 'Assemble (Java version: ${{ env.JAVA }})'
        run: ./gradlew assemble --no-daemon

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: 'Get this repo'
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA }}
          cache: ${{ env.BUILD_CACHE }}
      - name: 'Run tests (Java version: ${{ env.JAVA }})'
        run: |
          ./gradlew test --no-daemon
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Clean things
        run: |
          ./gradlew clean --no-daemon
      - name: 'Archive this artifact'
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./
          retention-days: 7
